=== oliverito11/DAM-1/LM/Trimestre3/XML/Ejercicios/Ejercicio 3/definicion.dtd
<!ELEMENT semanaSanta (viernesDolores, domingoRamos, lunes, martes, miercoles, jueves, viernes, sabado, domingoResurrec)>
<!ELEMENT viernesDolores (cofradias)>
<!ELEMENT domingoRamos (cofradias)>
<!ELEMENT lunes (cofradias)>
<!ELEMENT martes (cofradias)>
<!ELEMENT miercoles (cofradias)>
<!ELEMENT jueves (cofradias)>
<!ELEMENT viernes (cofradias)>
<!ELEMENT sabado (cofradias)>
<!ELEMENT domingoResurrec (cofradias)>
<!ELEMENT cofradias (pasos+)>
<!ATTLIST cofradias numeroCofrades CDATA #REQUIRED>
<!ATTLIST cofradias aÃ±oFundacion CDATA #REQUIRED>
<!ELEMENT pasos (nombrePaso, autorPaso, madera?, numFiguras?)>
<!ELEMENT nombrePaso (#PCDATA)>
<!ELEMENT autorPaso (#PCDATA)>
<!ELEMENT madera (#PCDATA)>
<!ELEMENT numFiguras (#PCDATA)>

=== oliverito11/DAM-1/LM/Trimestre3/XML/Ejercicios/Ejercicio 3/semanasanta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE semanaSanta SYSTEM "definicion.dtd">
<semanaSanta>
    <viernesDolores>
        <cofradias numeroCofrades="3" añoFundacion="212">
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
            </pasos>
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
                <madera></madera>
                <numFiguras></numFiguras>
            </pasos>
        </cofradias>
    </viernesDolores>
    <domingoRamos>
        <cofradias numeroCofrades="3" añoFundacion="212">
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
            </pasos>
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
                <madera></madera>
                <numFiguras></numFiguras>
            </pasos>
        </cofradias>
    </domingoRamos>
    <lunes>
        <cofradias numeroCofrades="3" añoFundacion="212">
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
            </pasos>
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
                <madera></madera>
                <numFiguras></numFiguras>
            </pasos>
        </cofradias>
    </lunes>
    <martes>
        <cofradias numeroCofrades="3" añoFundacion="212">
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
            </pasos>
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
                <madera></madera>
                <numFiguras></numFiguras>
            </pasos>
        </cofradias>
    </martes>
    <miercoles>
        <cofradias numeroCofrades="3" añoFundacion="212">
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
            </pasos>
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
                <madera></madera>
                <numFiguras></numFiguras>
            </pasos>
        </cofradias>
    </miercoles>
    <jueves>
        <cofradias numeroCofrades="3" añoFundacion="212">
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
            </pasos>
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
                <madera></madera>
                <numFiguras></numFiguras>
            </pasos>
        </cofradias>
    </jueves>
    <viernes>
        <cofradias numeroCofrades="3" añoFundacion="212">
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
            </pasos>
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
                <madera></madera>
                <numFiguras></numFiguras>
            </pasos>
        </cofradias>
    </viernes>
    <sabado>
        <cofradias numeroCofrades="3" añoFundacion="212">
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
            </pasos>
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
                <madera></madera>
                <numFiguras></numFiguras>
            </pasos>
        </cofradias>
    </sabado>
    <domingoResurrec>
        <cofradias numeroCofrades="3" añoFundacion="212">
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
            </pasos>
            <pasos>
                <nombrePaso></nombrePaso>
                <autorPaso></autorPaso>
                <madera></madera>
                <numFiguras></numFiguras>
            </pasos>
        </cofradias>
    </domingoResurrec>
</semanaSanta>
