=== oliverito11/DAM-1/LM/Trimestre3/XSD/Actividades/Actividad 11/Actividad 11 SOLUCION/ejercicio1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="departamento" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="trabajador" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="25"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>

                                        <xs:element name="apellidos">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="30"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    
                                        <xs:element name="dni">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:ID">
                                                
                                                <!-- Al ser de tipo ID, no puede empezar por número.
                                                    
                                                    Por eso, el DNI el XML será del tipo el DNI_12345678-J  por ejemplo -->
                                                <!--   <xs:pattern value="\d{8}-[TRWAGMYFPDXBNJZSQVHLCKE]"/> -->
                                                    <xs:pattern value="DNI_\d{8}-[TRWAGMYFPDXBNJZSQVHLCKE]"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>

                                        <xs:element name="direccion">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="35"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="telefono">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:pattern value="[0-9]{9}"/> <!-- 9 números del 0 al 9 -->
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <!-- Atributo numero normal (su valor se puede repetir) -->

                        <!-- IMPORTANTE Los atributos se establecen justo antes de cerrar "complexType" en el elemento al que 
                            pertenece. Antes definiremos las etiquetas (si las hay) -->
                        <xs:attribute name="nombreDep">    
                            <xs:simpleType>
                                <xs:restriction base="xs:string">    <!-- Enumeración conlos valores posibles del nombreDep -->
                                    <xs:enumeration value="Contabilidad"/>
                                    <xs:enumeration value="Informática"/>
                                    <xs:enumeration value="Electrónica"/>
                                    <xs:enumeration value="Márketing"/>
                                    <xs:enumeration value="Recursos Humanos"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== oliverito11/DAM-1/LM/Trimestre3/XSD/Actividades/Actividad 11/Actividad 11 SOLUCION/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio1.xsd">
  
    <departamento nombreDep="Informática">
        <trabajador>
            <nombre>Laura</nombre>
            <apellidos>Martin Lopez</apellidos>
            <dni>DNI_12345678-L</dni>
            <direccion>Calle Mayor 1 Zamora</direccion>
            <telefono>123456789</telefono>
        </trabajador>

        <trabajador>
            <nombre>Juan</nombre>
            <apellidos>Sánchez Rodrigo</apellidos>
            <dni>DNI_12395638-L</dni>
            <direccion>Calle Sol 1 Zamora</direccion>
            <telefono>123456789</telefono>
        </trabajador>

        <trabajador>
            <nombre>María</nombre>
            <apellidos>Martín Rodríguez</apellidos>
            <dni>DNI_22345678-L</dni>
            <direccion>Calle Luna 1 Zamora</direccion>
            <telefono>913456789</telefono>
        </trabajador>

      
        
    </departamento>

    <departamento nombreDep="Electrónica">
        <trabajador>
            <nombre>Juan</nombre>
            <apellidos>Martin Lopez</apellidos>
            <dni>DNI_91112211-M</dni>
            <direccion>Calle Mayor 1 Zamora</direccion>
            <telefono>123456789</telefono>
        </trabajador>

        <trabajador>
            <nombre>Sonia</nombre>
            <apellidos>Ruiz Ruiz</apellidos>
            <dni>DNI_99345638-L</dni>
            <direccion>Calle Mayor 1 Zamora</direccion>
            <telefono>123456789</telefono>
        </trabajador>

        <trabajador>
            <nombre>Juan</nombre>
            <apellidos>Martin Lopez</apellidos>
            <dni>DNI_32345678-L</dni>
            <direccion>Calle Mayor 1 Zamora</direccion>
            <telefono>913456789</telefono>
        </trabajador>

      
        
    </departamento>


    <departamento nombreDep="Recursos Humanos">
        <trabajador>
            <nombre>Alberto</nombre>
            <apellidos>Sanz Sanz</apellidos>
            <dni>DNI_99887766-L</dni>
            <direccion>Calle Mayor 1 Toro</direccion>
            <telefono>198456789</telefono>
        </trabajador>

        <trabajador>
            <nombre>Laura</nombre>
            <apellidos>Martin Lopez</apellidos>
            <dni>DNI_12945638-L</dni>
            <direccion>Calle Mayor 1 Zamora</direccion>
            <telefono>123456789</telefono>
        </trabajador>

        <trabajador>
            <nombre>Marta</nombre>
            <apellidos>Rodrigo Sánchez</apellidos>
            <dni>DNI_22345678-X</dni>
            <direccion>Calle Mayor 1 Sanabria</direccion>
            <telefono>913456789</telefono>
        </trabajador>

    </departamento>
          
</empresa>
