=== oliverito11/DAM-1/LM/Trimestre3/XSD/Actividades/Actividad 11/Actividad 11 SOLUCION/ejercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[aA-zZ ]{1,20}"/>  <!--Expresión regular para indicar que queremos de 1 a 20
                                            caracteres con mayúsculas, minúsculas y espacios en blanco -->
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="apellidos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[aA-zZ ]{1,40}"/>  <!-- No incluye vocales con tilde Se podrían incluir 
                                            con una expresión regular como [aA-zZáéíóúÁÉÍÓÚ ]{1,40} Ojo a la Ñ -->
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        
                            <xs:element name="dni">
                                <xs:simpleType>
                                    <xs:restriction base="xs:ID">
                                    
                                    <!-- Al ser de tipo ID, no puede empezar por número.
                                        
                                        Por eso, el DNI el XML será del tipo el DNI_12345678-J  por ejemplo -->
                                    <!--   <xs:pattern value="\d{8}-[TRWAGMYFPDXBNJZSQVHLCKE]"/> -->
                                        <xs:pattern value="DNI_\d{8}-[TRWAGMYFPDXBNJZSQVHLCKE]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="telefono" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:pattern value="[0-9]{9}"/> <!-- 9 números del 0 al 9 -->
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="email" minOccurs="0" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-z]{1,15}@[a-z]{1,25}\.[a-z]{2,4}"/> <!-- Para indicar que debe haber un .
                                            tenemos que ponerantes el carácter \.  pues si no, lo interpreta como cualquier varácter -->
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="provincia">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[aA-zZ ]{1,20}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                           
                        </xs:sequence>
                        <!-- No nos dan muchos detalles de codigo Persona. Si hiciese falta, se estalecerían más restricciones.
                            Como vemos, ponemos el atributo justo antes de cerrar la instrucción complexType correspondiente.
                            Al ser de tipo ID no nos permite repetirla -->
                        <xs:attribute name="codigoPersona" type="xs:ID" use="required"/>    
                           
                    </xs:complexType>

                        
                        <!-- Atributo numero normal (su valor se puede repetir) -->

                        <!-- IMPORTANTE Los atributos se establecen justo antes de cerrar "complexType" en el elemento al que 
                            pertenece. Antes definiremos las etiquetas (si las hay) -->
              
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== oliverito11/DAM-1/LM/Trimestre3/XSD/Actividades/Actividad 11/Actividad 11 SOLUCION/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio2.xsd">

    <persona codigoPersona="ab7">
        <nombre>Juan</nombre>
        <apellidos>Lopez Martin</apellidos>
        <dni>DNI_12345678-L</dni>
        <telefono>123456789</telefono>
        <telefono>123123123</telefono>
        <provincia>Leon</provincia>
    </persona>

    <persona codigoPersona="ab8">
        <nombre>Sandra</nombre>
        <apellidos>Rodrigo Rodrigo</apellidos>
        <dni>DNI_99345678-L</dni>
        <telefono>717171717</telefono>
        <email>sandra@gmail.com</email>
        <provincia>Leon</provincia>
    </persona>

</empresa>
