=== oliverito11/DAM-1/LM/Trimestre3/XML/Ejercicios/Ejercicio 4/Ejercicio 2/definicion.dtd
<!-- La biblioteca presta distintos recursos -->
<!ELEMENT biblioteca (recursos)+>

<!-- Estos recursos contendrán su código, tipo, título, autor y año de publicación -->
<!-- Puede haber más de un autor y puede o no aparecer su año de publicación -->
<!ELEMENT recursos (titulo, autor+, anyoPublicacion?)>

<!-- Los tipos solo pueden ser los especificados a continuación -->
<!ATTLIST recursos tipo (libro | cd | dvd | revista) #REQUIRED>

<!-- Los recursos tienen un identificador único para cada uno -->
<!ATTLIST recursos cod_recurso ID #REQUIRED>

<!-- Los demás elementos contendrán información -->
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT anyoPublicacion (#PCDATA)>

=== oliverito11/DAM-1/LM/Trimestre3/XML/Ejercicios/Ejercicio 4/Ejercicio 2/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "definicion.dtd">
<biblioteca>
    <recursos tipo="libro" cod_recurso="DQ">
        <titulo>Don Quijote de La Mancha</titulo>
        <autor>Desconocido</autor>
    </recursos>
    <recursos tipo="libro" cod_recurso="HI">
        <titulo>La Historia Interminable</titulo>
        <autor>Autor 1</autor>
        <autor>Autor 2</autor>
        <anyoPublicacion>1983</anyoPublicacion>
    </recursos>
    <recursos tipo="dvd" cod_recurso="SOAD">
        <titulo>Toxicity</titulo>
        <autor>System of a Down</autor>
        <anyoPublicacion>2000</anyoPublicacion>
    </recursos>
    <recursos tipo="dvd" cod_recurso="A7X">
        <titulo>Waking the fallen</titulo>
        <autor>Avenged Sevenfold</autor>
        <anyoPublicacion>2002</anyoPublicacion>
    </recursos>
    <recursos tipo="revista" cod_recurso="MC">
        <titulo>El Marca</titulo>
        <autor>El Marca</autor>
    </recursos>
    <recursos tipo="revista" cod_recurso="RV">
        <titulo>Revista</titulo>
        <autor>Pepe</autor>
        <autor>Pablo</autor>
        <autor>Juan</autor>
    </recursos>
    <recursos tipo="cd" cod_recurso="RL">
        <titulo>El Rey León</titulo>
        <autor>Disney</autor>
        <anyoPublicacion></anyoPublicacion>
    </recursos>
    <recursos tipo="cd" cod_recurso="ML">
        <titulo>Mulán</titulo>
        <autor>Disney</autor>
        <anyoPublicacion></anyoPublicacion>
    </recursos>
</biblioteca>
