=== oliverito11/DAM-1/LM/Trimestre3/Examen/Ejercicio 2/Ejercicio2.dtd
<!-- Etiqueta raíz de la que colgarán las distintas personas -->
<!ELEMENT empresa (persona+)>

<!-- Toda persona tiene los siguientes elementos -->
<!ELEMENT persona (nombre, apellidos, telefono+, email?, provincia)>
<!-- Además, tendrán un código único para cada una -->
<!ATTLIST persona codigoPersona ID #REQUIRED>

<!-- Elementos de las personas -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>

=== oliverito11/DAM-1/LM/Trimestre3/Examen/Ejercicio 2/Prueba1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "./Ejercicio2.dtd">

<empresa>
    <!-- Persona con varios teléfonos pero sin e-mail -->
    <persona codigoPersona="ab1">
        <nombre>Juan</nombre>
        <apellidos>López Martín</apellidos>
        <telefono>123456789</telefono>
        <telefono>123789456</telefono>
        <provincia>León</provincia>
    </persona>

    <!-- Persona con e-mail -->
    <persona codigoPersona="ab2">
        <nombre>Sandra</nombre>
        <apellidos>Rodrigo Rodrigo</apellidos>
        <telefono>919999999</telefono>
        <email>sandra@gmail.com</email>
        <provincia>León</provincia>
    </persona>
</empresa>
