=== oliverito11/DAM-1/LM/Trimestre3/XML/Ejercicios/Ejercicio 5/ejercicio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="instituto">
    <xs:complexType>
        <xs:sequence>
            <xs:element name = "alumno" maxOccurs = "unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name = "nombre" type = "xs:string" />
                        <xs:element name = "edad" type = "xs:integer" />
                        <xs:element name = "curso" type = "xs:string" />
                        <xs:element name = "matricula" type = "xs:long" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== oliverito11/DAM-1/LM/Trimestre3/XML/Ejercicios/Ejercicio 5/ejercicio.xml
<?xml version="1.0" encoding="UTF-8"?>
<instituto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejercicio.xsd">
    <alumno>
        <nombre>Oli</nombre>
        <edad>18</edad>
        <curso>DAM1</curso>
        <matricula>55222</matricula>
    </alumno>
    <alumno>
        <nombre>Pablo</nombre>
        <edad>20</edad>
        <curso>DAM2</curso>
        <matricula>66222</matricula>
    </alumno>
</instituto>
